### ISSUE TITLE
my_weight function explanation missing

### ISSUE THREAD

**Issue by RodanthiDamianaki** [softdevteam/guard-compatible-benchmarks#1]
Can you please explain in a comment what does the my_weight function?
How the weight is calculated?

Thank you!

**Comment by cfbolz** [comment]
Sorry, I am confused. Where is the my_weight function that you are talking about?

**Comment by RodanthiDamianaki** [comment]
I'm sorry. I can't find where it is, but thank you for replying. You can close and delete the issue.
